spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autotravalserverdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: bcgg
    password: bcgg

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  jwt:
    secret : l+R4n4VF6V+Z981hkoYEpTlx5yvyo8oOYDzP5HCirAQ=