

### sign up
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "kim",
  "password": "qwert"
}
### sign in
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "kim",
  "password": "qwert"
}

### create Schedule
POST http://localhost:8080/schedule
Content-Type: application/json

{
  "memberId": 123,
  "scheduleName": "My Schedule",
  "destination": [
    {
      "destinationName": "Destination 1",
      "destinationAddress": "123 Main St.",
      "destinationTime": "2023-03-15T15:30:00",
      "lat": 33.0,
      "lng": 125.0
    },
    {
      "destinationName": "Destination 2",
      "destinationAddress": "456 Second St.",
      "destinationTime": "2023-03-15T16:30:00",
      "lat": 33.0,
      "lng": 125.0
    }
  ],
  "scheduleStatus": "ACTIVE"
}

###
GET http://localhost:8080/tour