spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auto_travel_tour?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root673254
    tomcat:
      url:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    defer-datasource-initialization: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  tour:
    key: mnIS24cpM2UmU4vtwIRpoUwKCuV9tNRupzWGtOnE3yHwD7%2FAJpZc1nigqPFbDxjsmI1%2B4r9vYpE3ioQAt%2F0Lsw%3D%3D




