spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auto_travel_schedule?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root673254

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: emVyby1jYWxvcmllLXByZXNpbW1vbi10cmVlLWNhdC1pcy12ZXJ5LWN1dGUK

server:
  port: 8081
